export const iconsArray = [
    '500px',
    'address-book-o',
    'adjust',
    'adn',
    'align-right',
    'amazon',
    'ambulance',
    'american-sign-language-interpreting',
    'anchor',
    'android',
    'angellist',
    'th-large',
    'th-list',
    'themeisle',
    'thermometer',
    'arrow-circle-o-left'];

export const iconsArray2 = [
    'arrow-circle-o-right',
    'arrow-circle-o-up',
    'arrow-circle-right',
    'stop-circle',
    'stop-circle-o',
    'street-view',
    'strikethrough',
    'stumbleupon',
    'stumbleupon-circle',
    'subscript',
    'subway',
    'suitcase',
    'sun-o',
    'superpowers',
    'superscript',
    'support'];

export const iconsArray3 = [
    'bullhorn',
    'bullseye',
    'bus',
    'buysellads',
    'cab',
    'calculator',
    'calendar-check-o',
    'camera-retro',
    'car',
    'caret-down',
    'cc-amex',
    'cc-diners-club',
    'cc-discover',
    'cc-jcb',
    'cc-mastercard',
    'cc-paypal',
    'cc-stripe',
    'cc-visa',
    'google-plus'];
